// Generated by CoffeeScript 2.5.1
// compile with coffee -b -c CtoCS.coffee and load it in node with .load CtoCS.js or copy the js file into a browser console
// or run coffee -b -c -w *.coffee in the VS Code Terminal and split *.coffee and and *.js

// c++ rand() function
var getAllResults, rand;

rand = function() {
  return Math.floor(Math.random() * 2 ** 16);
};

// try to print all results
getAllResults = function(func, iterations) {
  var i, out, output, ref;
  if (typeof func === "string") {
    func = new Function("return " + func);
  }
  out = [];
  for (i = 0, ref = iterations; (0 <= ref ? i < ref : i > ref); 0 <= ref ? i++ : i--) {
    output = func();
    if (!out.includes(output)) {
      out.push(output);
    }
  }
  return out.sort();
};
